--#SET TERMINATOR ;

-- =============================================
-- SaveToDB Framework Extension for IBM DB2
-- Version 10.6, December 13, 2022
--
-- Copyright 2022 Gartle LLC
--
-- License: MIT
-- =============================================

DELETE FROM XLS.FORMATS   WHERE TABLE_SCHEMA = 'XLS' AND TABLE_NAME IN ('VIEW_COLUMNS', 'VIEW_FORMATS', 'VIEW_HANDLERS', 'VIEW_OBJECTS', 'VIEW_QUERIES', 'VIEW_TRANSLATIONS', 'VIEW_WORKBOOKS');
DELETE FROM XLS.HANDLERS  WHERE TABLE_SCHEMA = 'XLS' AND TABLE_NAME IN ('VIEW_COLUMNS', 'VIEW_FORMATS', 'VIEW_HANDLERS', 'VIEW_OBJECTS', 'VIEW_QUERIES', 'VIEW_TRANSLATIONS', 'VIEW_WORKBOOKS', 'SAVETODB_FRAMEWORK_EXTENSION');
DELETE FROM XLS.WORKBOOKS WHERE TABLE_SCHEMA = 'XLS' AND NAME IN ('savetodb_user_configuration.xlsx');

DELETE FROM XLS.HANDLERS WHERE TABLE_SCHEMA = 'XLS' AND TABLE_NAME = 'USERS' AND HANDLER_NAME IN ('XL_ACTIONS_SET_EXTENDED_ROLE_PERMISSIONS', 'XL_ACTIONS_REVOKE_EXTENDED_ROLE_PERMISSIONS');

DROP PROCEDURE XLS.XL_ACTIONS_SET_EXTENDED_ROLE_PERMISSIONS;
DROP PROCEDURE XLS.XL_ACTIONS_REVOKE_EXTENDED_ROLE_PERMISSIONS;

DROP VIEW XLS.VIEW_COLUMNS;
DROP VIEW XLS.VIEW_FORMATS;
DROP VIEW XLS.VIEW_HANDLERS;
DROP VIEW XLS.VIEW_OBJECTS;
DROP VIEW XLS.VIEW_QUERIES;
DROP VIEW XLS.VIEW_TRANSLATIONS;
DROP VIEW XLS.VIEW_WORKBOOKS;

echo SaveToDB Framework Extension removed
